all:
  hosts:
    slave01:
      ip: 10.98.0.104
    slave02:
      ip: 10.98.0.105
    slave03:
      ip: 10.98.0.52
    master01:
      ip: 10.98.0.101
    master02:
      ip: 10.98.0.102
    master03:
      ip: 10.98.0.103
    loadbalancer:
      ip: 10.98.0.100
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    kube-masters:
      hosts:
        master01:
        master02:
        master03:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    kube-slaves:
      hosts:
        slave01:
        slave02:
        slave03:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    loadblancer:
      loadbalancer:
    etcd:
      hosts:
        master01:
        master02:
        master03:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    k8s-cluster:
      children:
        kube-masters:
        kube-slaves:
