all:
  hosts:
    node1:
      ip: 10.98.0.20
    node2:
      ip: 10.98.0.21
    node3:
      ip: 10.98.0.22
    node4:
      ip: 10.98.0.16
    node5:
      ip: 10.98.0.17
    node6:
      ip: 10.98.0.18
    loadbalancer:
      ip: 10.98.0.19
  children:
    kube-masters:
      hosts:
        node4:
        node5:
        node6:
    kube-slaves:
      hosts:
        node1:
        node2:
        node3:
    loadblancer:
      loadbalancer:
    etcd:
      hosts:
        node4:
        node5:
        node6:
    k8s-cluster:
      children:
        kube-masters:
        kube-slaves:
