all:
  hosts:
    slave01:
      ip: 10.98.0.20
    slave02:
      ip: 10.98.0.21
    slave03:
      ip: 10.98.0.22
    master01:
      ip: 10.98.0.16
    master02:
      ip: 10.98.0.17
    master03:
      ip: 10.98.0.18
    loadbalancer:
      ip: 10.98.0.19
  children:
    kube-masters:
      hosts:
        master01:
        master02:
        master03:
    kube-slaves:
      hosts:
        slave01:
        slave02:
        slave03:
    loadblancer:
      loadbalancer:
    etcd:
      hosts:
        master01:
        master02:
        master03:
    k8s-cluster:
      children:
        kube-masters:
        kube-slaves:
