---
- hosts: all
  vars:
   users:
     - popopame


#Installation of needed packet and update of the distant host
  tasks:
   - name: "Installation of 3 packet that will help us later"
     yum:
       name: "{{ packages }}"
     vars:
       packages:
         - net-tools
         - conntrack
         - socat
         - wget
         - vim
         - epel-release
   - name: "Update of the System"
     yum:
       name: "*"
       state: latest
       update_cache: yes

#Creation of user/s referenced in "users" var , and creation of their ssh key

   - name: "Create user accounts and add users to admin groups"
     user:
       name: "{{ item }}"
       groups: "wheel"
     with_items: "{{ users }}"
   - name: "Add authorized key"
     authorized_key:
       user: "{{ item }}"
       state: "present"
       key: "{{ lookup('file', '/KHW/ansible/inventory/'+item+'.key.pub') }}"
     with_items: "{{ users }}"
   - name: "Allow admin users to sudo without password"
     lineinfile:
       dest: "/etc/sudoers"
       state: "present"
       regexp: "^%wheel"
       line: "%wheel ALL=(ALL) NOPASSWD: ALL"

#Deploiement of the certificate and the key on the hosts
- hosts: kube-masters
  tasks:
     - name: "Upload the api key on the Masters nodes"
       copy:
            src: "/KHW/pki/api/kubernetes-key.pem"
            dest: "/"
     - name: "Copy the api certificate on the masters"
       copy:
            src: "/KHW/pki/api/kubernetes.pem"
            dest: "/"
     - name: "Copy the CA on the master"
       copy:
            src: "/KHW/pki/ca/ca.pem"
            dest: "/"
     - name: "Copy the CA  key on the master"
       copy:
            src: "/KHW/pki/ca/ca-key.pem"
            dest: "/"


     - name: "Copy the service account key"
       copy:
            src: "/KHW/pki/service-account/service-account-key.pem"
            dest: "/"
     - name: "Copy the service account certificate"
       copy:
            src: "/KHW/pki/service-account/service-account.pem"
            dest: "/"

- hosts: kube-slaves
  tasks:
      - name: "Copy the ca certificate on the slaves hosts"
        copy:
          src: "/KHW/pki/ca/ca.pem"
          dest: "/"

- hosts: slave01
  tasks:
     - name: "Copy the slave01 clients key on slave01"
       copy:
            src: "/KHW/pki/clients/slave01-key.pem"
            dest: "/"
     - name: "Copy the slave01 clients certificate on slave01"
       copy:
            src: "/KHW/pki/clients/slave01.pem"
            dest: "/"

- hosts: slave02
  tasks:
    - name: "Copy the slave02 clients key on slave02"
      copy:
           src: "/KHW/pki/clients/slave02-key.pem"
           dest: "/"
    - name: "Copy the slave02 clients certificate on slave01"
      copy:
           src: "/KHW/pki/clients/slave02.pem"
           dest: "/"

- hosts: slave03
  tasks:
    - name: "Copy the slave03 clients key on slave03"
      copy:
           src: "/KHW/pki/clients/slave03-key.pem"
           dest: "/"
    - name: "Copy the slave03 clients certificate on slave03"
      copy:
           src: "/KHW/pki/clients/slave03.pem"
           dest: "/"
