---
#Copy the admin , controller and scheduler kubeconfig file on the masters nodes
#Second task will deploy the encryption key on all the masters
- hosts: kube-masters
  tasks:
     - name: "Upload the Admin, Controller and Sheduler kubeconfig on Master"
       copy:
            src: "/KHW/{{ item }}"
            dest: "/"
       with_items:
         ['configs/admin/admin.kubeconfig','configs/controller/kube-controller-manager.kubeconfig','configs/scheduler/kube-scheduler.kubeconfig']

     - name: "Upload the encryption Key"
       copy:
            src: "/KHW/configs/encrypt/encryption-config.yaml"
            dest: "/"

#Ths below will copy the Proxy Kubeconfig on the slaves nodes
#And the second Task will deploythr clients Kubeconfig on each respective note
- hosts: kube-slaves
  tasks:
      - name: "Copy the proxy kubeconfig on the slaves nodes"
        copy:
            src: "/KHW/configs/proxy/kube-proxy.kubeconfig"
            dest: "/"
      - name: "Copy the client kubeconfig on each node"
        copy:
            src: "/KHW/configs/clients/{{ inventory_hostname }}.kubeconfig"
            dest: "/"
